### PR TITLE
[bugfix] Fix Ember.deprecate syntax

### LINKED ISSUE #224: Deprecations don't actually seem to be called
I was upgrading this addon on an app that uses ember-cli-deprecation-workflow to error on deprecation by default. I noticed our app uses `import test from 'ember-sinon-qunit/test-support/test';` but this was not raising a deprecation.

It looks like the [deprecation syntax](https://api.emberjs.com/ember/3.12/functions/@ember%2Fdebug/deprecate) is being used [incorrectly](https://github.com/elwayman02/ember-sinon-qunit/blob/9544a3cc958fdd3c59da43cabd8115a5bc637fb4/addon-test-support/test.js#L9) - as it stands now, the `options` object is being used as the `test` boolean and will always be truthy (no deprecation raised):

```es6
deprecate(
  'This pattern is now deprecated. Please import the `setupSinon` method instead.', 
  {
    id: 'ember-sinon-qunit.test'
  }
);
```

Should be:

```es6
deprecate(
  'This pattern is now deprecated. Please import the `setupSinon` method instead.', 
  false, 
  {
    id: 'ember-sinon-qunit.test'
  }
);
```

I'm happy to submit a PR, just wanted to confirm in case this was deliberate.

### PR DESCRIPTION
**Pull request by gorner**
Resolves #224.

### CODE REVIEW

File: tests/unit/ember-sinon-qunit-test.js [hunk 1]
```diff
@@ -2,6 +2,8 @@ import { module } from 'qunit';
 import { resolve } from 'rsvp';
 import test from 'ember-sinon-qunit/test-support/test';
 import assertSinonInTestContext from '../helpers/assert-sinon-in-test-context';
+import Ember from 'ember';
```
Comment (elwayman02) [inline tests/unit/ember-sinon-qunit-test.js]: I *think* you can do `import debug from '@ember/debug';` instead of pulling in Ember here. Looking through the code, `debug` is exported as part of an object, which is how we're able to use destructuring to import it.

https://github.com/emberjs/ember.js/blob/v3.12.0/packages/%40ember/debug/index.ts#L342

**Comment by elwayman02** [comment]
@gorner this looks great! Just one minor improvement suggestion, then :shipit:

File: tests/unit/ember-sinon-qunit-test.js (hunk 1 above)
Comment (gorner) [reply tests/unit/ember-sinon-qunit-test.js]: Unfortunately not:

```
Build Error (broccoli-persistent-filter:Babel > [Babel: ember-sinon-qunit]) in dummy/tests/unit/ember-sinon-qunit-test.js

/Users/gorner/Development/ember-sinon-qunit/dummy/tests/unit/ember-sinon-qunit-test.js: @ember/debug does not have a default export
```

I'm not surprised as it still compiles down to `Ember.deprecate` when built:

```
define("ember-sinon-qunit/test", ["exports", "ember-qunit", "ember-sinon-qunit/utils/config"], function (_exports, _emberQunit, _config) {
  "use strict";

  Object.defineProperty(_exports, "__esModule", {
    value: true
  });
  _exports.default = test;
  // Global sinon config setup
  (0, _config.commonConfig)();

  function test(testName, callback) {
    (true && !(false) && Ember.deprecate('This pattern is now deprecated. Please import the `setupSinon` method instead.', false, {
      id: 'ember-sinon-qunit.test',
      until: '5.0.0',
      url: 'https://github.com/elwayman02/ember-sinon-qunit#migration-from-older-versions-of-ember-sinon-qunit'
    }));
    (0, _config.wrapTest)(testName, callback, _emberQunit.test);
  }
});
```

Comment (elwayman02) [reply tests/unit/ember-sinon-qunit-test.js]: RIP
